project:
  type: website
  output-dir: docs

website:
  title: "i9wa4's slides"
  site-url: "https://i9wa4.github.io/slides/"
  navbar:
    left:
      - href: https://i9wa4.github.io
        text: Top
  page-footer:
    left: "Built with [Quarto](https://quarto.org/)"
    center: "&copy;2024, i9wa4"
    right:
      - icon: github
        href: https://github.com/i9wa4
      - icon: twitter-x
        href: https://x.com/i9wa4_

lang: en
date-format: iso
theme: flatly
