project:
  type: website
  output-dir: docs

website:
  title: "Slides"
  site-url: "https://i9wa4.github.io/slides/"
  page-footer:
    left: "Built with [Quarto](https://quarto.org/)"
    center: "&copy;2024, i9wa4"
    right:
      - icon: github
        href: https://github.com/i9wa4
      - icon: twitter
        href: https://x.com/i9wa4_

format:
  html:
    theme: cosmo

lang: en
date-format: iso
